queue:
  host: "127.0.0.1"
  port: "6379"
  recent: 100   # how many entries to keep in the recent changelog list
  token_ttl: 36000
auth:
  provider: "Sinatra::CasAuth"
  config: 
    base_url: 'https://secure.its.yale.edu/cas'
    ticket_store_config:
      storage_dir: '.'
# define the schema for validation
# see also: https://github.com/hoxworth/json-schema
# see also: http://tools.ietf.org/html/draft-zyp-json-schema-04
schema: 
  type: "object"
  required:
    - user
    - hostname
    - criticality
    - description
  properties:
      user:
        type: string
      date:
        type: string
      hostname:
        type: string
      tag:
        type: string
      criticality:
        type: integer
      description:
        type: string
      body:
        type: string
